apiVersion: v1
kind: Service
metadata:
  name: toa-website
  namespace: toa-production
  labels:
    app: toa-website
    environment: production
spec:
  type: LoadBalancer
  selector:
    app: toa-website
    version: blue  # Switch to 'green' for blue-green deployment
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 443
    targetPort: 5000
    protocol: TCP
    name: https
