/**
 * Generate client/public/sitemap.xml from the real content data files.
 *
 * Why this exists: the sitemap was hand-maintained and drifted badly out of
 * sync — it advertised 8 character pages where 7 of the slugs no longer
 * existed (rendering thin "not found" pages that Google crawls but won't
 * index), omitted all the real characters plus /campaigns, /videos and
 * /podcast, and listed noindex/private pages (/track-order, /legal/*).
 *
 * Driving the sitemap from characters.json / campaigns.json / episodes.json
 * keeps it correct automatically. Wired into `build:client` so every
 * production build ships a fresh sitemap.
 *
 * Run manually: npm run sitemap:generate
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataDir = resolve(__dirname, '../client/src/data');
const outFile = resolve(__dirname, '../client/public/sitemap.xml');

const BASE = 'https://talesofaneria.com';

type DataRecord = Record<string, unknown>;

/** Read a JSON data file that is either an array or `{ <key>: [...] }`. */
function loadList(file: string, key: string): DataRecord[] {
  const raw: unknown = JSON.parse(readFileSync(resolve(dataDir, file), 'utf8'));
  if (Array.isArray(raw)) {return raw as DataRecord[];}
  const obj = raw as DataRecord;
  // key is a hardcoded literal supplied by this script, not external input.
  // eslint-disable-next-line security/detect-object-injection
  const keyed = obj[key];
  if (Array.isArray(keyed)) {return keyed as DataRecord[];}
  return Object.values(obj).filter(
    (v): v is DataRecord => !!v && typeof v === 'object',
  );
}

/** Read a string-ish field that may live under one of several keys. */
function pick(record: DataRecord, ...keys: string[]): string | undefined {
  for (const k of keys) {
    // eslint-disable-next-line security/detect-object-injection
    const v = record[k];
    if (typeof v === 'string' && v.length > 0) {return v;}
    if (typeof v === 'number') {return String(v);}
  }
  return undefined;
}

interface UrlEntry {
  loc: string;
  changefreq: string;
  priority: string;
}

const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

const characters = loadList('characters.json', 'characters');
const campaigns = loadList('campaigns.json', 'campaigns');
const episodes = loadList('episodes.json', 'episodes');

const urls: UrlEntry[] = [];
const add = (path: string, changefreq: string, priority: string) =>
  urls.push({ loc: `${BASE}${path}`, changefreq, priority });

// Static, indexable marketing/content pages.
// NOTE: intentionally excluded — they are noindex and/or private:
//   /track-order, /legal/privacy, /legal/tos, /checkout*, /admin*
add('/', 'weekly', '1.0');
add('/characters', 'weekly', '0.9');
add('/campaigns', 'weekly', '0.9');
add('/videos', 'weekly', '0.8');
add('/podcast', 'weekly', '0.8');
add('/shop', 'weekly', '0.8');
add('/sponsorship', 'monthly', '0.7');
add('/sponsors', 'monthly', '0.7');
add('/press-kit', 'monthly', '0.7');

// Character detail pages (one per real character).
for (const c of characters) {
  const slug = pick(c, 'slug', 'id');
  if (slug) {add(`/characters/${slug}`, 'monthly', '0.7');}
}

// Campaign detail pages.
for (const c of campaigns) {
  const slug = pick(c, 'slug', 'id');
  if (slug) {add(`/campaigns/${slug}`, 'weekly', '0.8');}
}

// Episode detail pages: /campaigns/:slug/episodes/:episodeNumber
for (const e of episodes) {
  const slug = pick(e, 'campaignSlug', 'campaign', 'campaignId');
  const num = pick(e, 'episodeNumber', 'number');
  if (slug && num) {
    add(`/campaigns/${slug}/episodes/${num}`, 'monthly', '0.6');
  }
}

const body = urls
  .map(
    (u) =>
      `  <url>\n` +
      `    <loc>${u.loc}</loc>\n` +
      `    <changefreq>${u.changefreq}</changefreq>\n` +
      `    <priority>${u.priority}</priority>\n` +
      `    <lastmod>${today}</lastmod>\n` +
      `  </url>`,
  )
  .join('\n\n');

const xml =
  `<?xml version="1.0" encoding="UTF-8"?>\n` +
  `<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"\n` +
  `        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">\n\n` +
  `  <!-- Generated by scripts/generate-sitemap.ts — do not edit by hand. -->\n\n` +
  `${body}\n\n` +
  `</urlset>\n`;

writeFileSync(outFile, xml, 'utf8');
console.info(
  `Wrote ${urls.length} URLs to ${outFile} ` +
    `(${characters.length} characters, ${campaigns.length} campaigns, ${episodes.length} episodes)`,
);
